# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autowork.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1127, 700)
        Form.setStyleSheet("background-color:rgb(235, 238, 255)")
        self.lbl_auw_02 = QtWidgets.QLabel(Form)
        self.lbl_auw_02.setGeometry(QtCore.QRect(220, 60, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_02.setFont(font)
        self.lbl_auw_02.setStyleSheet("background-color:#fff;")
        self.lbl_auw_02.setObjectName("lbl_auw_02")
        self.lbl_auw_03 = QtWidgets.QLabel(Form)
        self.lbl_auw_03.setGeometry(QtCore.QRect(340, 60, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_03.setFont(font)
        self.lbl_auw_03.setStyleSheet("background-color:#fff;")
        self.lbl_auw_03.setText("")
        self.lbl_auw_03.setObjectName("lbl_auw_03")
        self.btn_auw_stop = QtWidgets.QPushButton(Form)
        self.btn_auw_stop.setGeometry(QtCore.QRect(30, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_auw_stop.setFont(font)
        self.btn_auw_stop.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_auw_stop.setObjectName("btn_auw_stop")
        self.btn_auw_back = QtWidgets.QPushButton(Form)
        self.btn_auw_back.setGeometry(QtCore.QRect(30, 190, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_auw_back.setFont(font)
        self.btn_auw_back.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_auw_back.setObjectName("btn_auw_back")
        self.btn_auw_change = QtWidgets.QPushButton(Form)
        self.btn_auw_change.setGeometry(QtCore.QRect(30, 140, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_auw_change.setFont(font)
        self.btn_auw_change.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_auw_change.setObjectName("btn_auw_change")
        self.lbl_auw3 = QtWidgets.QLabel(Form)
        self.lbl_auw3.setGeometry(QtCore.QRect(100, 370, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw3.setFont(font)
        self.lbl_auw3.setStyleSheet("background-color:#fff;")
        self.lbl_auw3.setObjectName("lbl_auw3")
        self.lbl_auw_01 = QtWidgets.QLabel(Form)
        self.lbl_auw_01.setGeometry(QtCore.QRect(30, 20, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_auw_01.setFont(font)
        self.lbl_auw_01.setStyleSheet("background-color:rgb(200, 255, 176);")
        self.lbl_auw_01.setObjectName("lbl_auw_01")
        self.btn_auw_continue = QtWidgets.QPushButton(Form)
        self.btn_auw_continue.setGeometry(QtCore.QRect(30, 90, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_auw_continue.setFont(font)
        self.btn_auw_continue.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_auw_continue.setObjectName("btn_auw_continue")
        self.tbl_quantity = QtWidgets.QTableWidget(Form)
        self.tbl_quantity.setGeometry(QtCore.QRect(210, 370, 421, 281))
        self.tbl_quantity.setStyleSheet("background-color:rgb(251, 255, 205)")
        self.tbl_quantity.setRowCount(5)
        self.tbl_quantity.setColumnCount(4)
        self.tbl_quantity.setObjectName("tbl_quantity")
        self.lbl_img = QtWidgets.QLabel(Form)
        self.lbl_img.setGeometry(QtCore.QRect(340, 120, 301, 221))
        self.lbl_img.setStyleSheet("background-color:#fff;")
        self.lbl_img.setText("")
        self.lbl_img.setObjectName("lbl_img")
        self.lbl_auw_3 = QtWidgets.QLabel(Form)
        self.lbl_auw_3.setGeometry(QtCore.QRect(680, 60, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_3.setFont(font)
        self.lbl_auw_3.setStyleSheet("background-color:#fff;")
        self.lbl_auw_3.setObjectName("lbl_auw_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(850, 60, 211, 70))
        self.textEdit.setStyleSheet("background-color:#fff;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(850, 170, 211, 70))
        self.textEdit_2.setStyleSheet("background-color:#fff;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.lbl_auw_4 = QtWidgets.QLabel(Form)
        self.lbl_auw_4.setGeometry(QtCore.QRect(680, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_4.setFont(font)
        self.lbl_auw_4.setStyleSheet("background-color:#fff;")
        self.lbl_auw_4.setObjectName("lbl_auw_4")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(850, 280, 211, 70))
        self.textEdit_3.setStyleSheet("background-color:#fff;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.lbl_auw_5 = QtWidgets.QLabel(Form)
        self.lbl_auw_5.setGeometry(QtCore.QRect(680, 280, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_5.setFont(font)
        self.lbl_auw_5.setStyleSheet("background-color:#fff;")
        self.lbl_auw_5.setObjectName("lbl_auw_5")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(850, 390, 211, 70))
        self.textEdit_4.setStyleSheet("background-color:#fff;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.lbl_auw_6 = QtWidgets.QLabel(Form)
        self.lbl_auw_6.setGeometry(QtCore.QRect(680, 390, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_6.setFont(font)
        self.lbl_auw_6.setStyleSheet("background-color:#fff;")
        self.lbl_auw_6.setObjectName("lbl_auw_6")
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setGeometry(QtCore.QRect(850, 490, 211, 70))
        self.textEdit_5.setStyleSheet("background-color:#fff;")
        self.textEdit_5.setObjectName("textEdit_5")
        self.lbl_auw_7 = QtWidgets.QLabel(Form)
        self.lbl_auw_7.setGeometry(QtCore.QRect(680, 490, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_7.setFont(font)
        self.lbl_auw_7.setStyleSheet("background-color:#fff;")
        self.lbl_auw_7.setObjectName("lbl_auw_7")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_auw_02.setText(_translate("Form", "Loại hàng"))
        self.btn_auw_stop.setText(_translate("Form", "Tạm dừng"))
        self.btn_auw_back.setText(_translate("Form", "Quay lại"))
        self.btn_auw_change.setText(_translate("Form", "Chuyển chế độ"))
        self.lbl_auw3.setText(_translate("Form", "Số lượng"))
        self.lbl_auw_01.setText(_translate("Form", "Tự động"))
        self.btn_auw_continue.setText(_translate("Form", "Tiếp tục"))
        self.lbl_auw_3.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_4.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_5.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_6.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_7.setText(_translate("Form", "Thông tin hàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
