# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'byhandwork.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1211, 778)
        Form.setStyleSheet("background-color:rgb(235, 238, 255)")
        self.lbl_byh_02 = QtWidgets.QLabel(Form)
        self.lbl_byh_02.setGeometry(QtCore.QRect(30, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_02.setFont(font)
        self.lbl_byh_02.setStyleSheet("background-color:#fff;")
        self.lbl_byh_02.setObjectName("lbl_byh_02")
        self.btn_byh_set = QtWidgets.QPushButton(Form)
        self.btn_byh_set.setGeometry(QtCore.QRect(640, 70, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_set.setFont(font)
        self.btn_byh_set.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_set.setObjectName("btn_byh_set")
        self.cb_motor = QtWidgets.QComboBox(Form)
        self.cb_motor.setGeometry(QtCore.QRect(380, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motor.setFont(font)
        self.cb_motor.setStyleSheet("background-color:#fff;")
        self.cb_motor.setObjectName("cb_motor")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.cb_motor.addItem("")
        self.btn_byh_up = QtWidgets.QPushButton(Form)
        self.btn_byh_up.setGeometry(QtCore.QRect(470, 230, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_up.setFont(font)
        self.btn_byh_up.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_up.setObjectName("btn_byh_up")
        self.btn_byh_left = QtWidgets.QPushButton(Form)
        self.btn_byh_left.setGeometry(QtCore.QRect(390, 270, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_left.setFont(font)
        self.btn_byh_left.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_left.setObjectName("btn_byh_left")
        self.btn_byh_down = QtWidgets.QPushButton(Form)
        self.btn_byh_down.setGeometry(QtCore.QRect(470, 310, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_down.setFont(font)
        self.btn_byh_down.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_down.setObjectName("btn_byh_down")
        self.btn_byh_right = QtWidgets.QPushButton(Form)
        self.btn_byh_right.setGeometry(QtCore.QRect(550, 270, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_right.setFont(font)
        self.btn_byh_right.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_right.setObjectName("btn_byh_right")
        self.lbl_byh_05 = QtWidgets.QLabel(Form)
        self.lbl_byh_05.setGeometry(QtCore.QRect(380, 180, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_05.setFont(font)
        self.lbl_byh_05.setStyleSheet("background-color:#fff;")
        self.lbl_byh_05.setObjectName("lbl_byh_05")
        self.lbl_byh_03 = QtWidgets.QLabel(Form)
        self.lbl_byh_03.setGeometry(QtCore.QRect(30, 180, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_03.setFont(font)
        self.lbl_byh_03.setStyleSheet("background-color:#fff;")
        self.lbl_byh_03.setObjectName("lbl_byh_03")
        self.lbl_byh_04 = QtWidgets.QLabel(Form)
        self.lbl_byh_04.setGeometry(QtCore.QRect(30, 470, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_04.setFont(font)
        self.lbl_byh_04.setStyleSheet("background-color:#fff;")
        self.lbl_byh_04.setObjectName("lbl_byh_04")
        self.lbl_byh_01 = QtWidgets.QLabel(Form)
        self.lbl_byh_01.setGeometry(QtCore.QRect(10, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_byh_01.setFont(font)
        self.lbl_byh_01.setStyleSheet("background-color:rgb(200, 255, 176);")
        self.lbl_byh_01.setObjectName("lbl_byh_01")
        self.btn_byh_back = QtWidgets.QPushButton(Form)
        self.btn_byh_back.setGeometry(QtCore.QRect(1030, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_back.setFont(font)
        self.btn_byh_back.setStyleSheet("background-color:rgb(85, 255, 127)")
        self.btn_byh_back.setObjectName("btn_byh_back")
        self.plt_speed = QtWidgets.QPlainTextEdit(Form)
        self.plt_speed.setGeometry(QtCore.QRect(520, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plt_speed.setFont(font)
        self.plt_speed.setStyleSheet("background-color:#fff;")
        self.plt_speed.setPlainText("")
        self.plt_speed.setObjectName("plt_speed")
        self.tbl_quantity = QtWidgets.QTableWidget(Form)
        self.tbl_quantity.setGeometry(QtCore.QRect(150, 470, 421, 271))
        self.tbl_quantity.setStyleSheet("background-color:rgb(251, 255, 205)")
        self.tbl_quantity.setRowCount(5)
        self.tbl_quantity.setColumnCount(4)
        self.tbl_quantity.setObjectName("tbl_quantity")
        self.txt_1 = QtWidgets.QTextEdit(Form)
        self.txt_1.setGeometry(QtCore.QRect(880, 210, 231, 70))
        self.txt_1.setStyleSheet("background-color:#fff;")
        self.txt_1.setObjectName("txt_1")
        self.txt_5 = QtWidgets.QTextEdit(Form)
        self.txt_5.setGeometry(QtCore.QRect(880, 640, 231, 70))
        self.txt_5.setStyleSheet("background-color:#fff;")
        self.txt_5.setObjectName("txt_5")
        self.txt_4 = QtWidgets.QTextEdit(Form)
        self.txt_4.setGeometry(QtCore.QRect(880, 540, 231, 70))
        self.txt_4.setStyleSheet("background-color:#fff;")
        self.txt_4.setObjectName("txt_4")
        self.lbl_byh_6 = QtWidgets.QLabel(Form)
        self.lbl_byh_6.setGeometry(QtCore.QRect(720, 640, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_6.setFont(font)
        self.lbl_byh_6.setStyleSheet("background-color:#fff;")
        self.lbl_byh_6.setObjectName("lbl_byh_6")
        self.lbl_byh_4 = QtWidgets.QLabel(Form)
        self.lbl_byh_4.setGeometry(QtCore.QRect(720, 430, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_4.setFont(font)
        self.lbl_byh_4.setStyleSheet("background-color:#fff;")
        self.lbl_byh_4.setObjectName("lbl_byh_4")
        self.lbl_byh_2 = QtWidgets.QLabel(Form)
        self.lbl_byh_2.setGeometry(QtCore.QRect(720, 210, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_2.setFont(font)
        self.lbl_byh_2.setStyleSheet("background-color:#fff;")
        self.lbl_byh_2.setObjectName("lbl_byh_2")
        self.lbl_byh_3 = QtWidgets.QLabel(Form)
        self.lbl_byh_3.setGeometry(QtCore.QRect(720, 330, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_3.setFont(font)
        self.lbl_byh_3.setStyleSheet("background-color:#fff;")
        self.lbl_byh_3.setObjectName("lbl_byh_3")
        self.lbl_byh_5 = QtWidgets.QLabel(Form)
        self.lbl_byh_5.setGeometry(QtCore.QRect(720, 530, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_5.setFont(font)
        self.lbl_byh_5.setStyleSheet("background-color:#fff;")
        self.lbl_byh_5.setObjectName("lbl_byh_5")
        self.txt_2 = QtWidgets.QTextEdit(Form)
        self.txt_2.setGeometry(QtCore.QRect(880, 320, 231, 70))
        self.txt_2.setStyleSheet("background-color:#fff;")
        self.txt_2.setObjectName("txt_2")
        self.txt_3 = QtWidgets.QTextEdit(Form)
        self.txt_3.setGeometry(QtCore.QRect(880, 430, 231, 70))
        self.txt_3.setStyleSheet("background-color:#fff;")
        self.txt_3.setObjectName("txt_3")
        self.lbl_img = QtWidgets.QLabel(Form)
        self.lbl_img.setGeometry(QtCore.QRect(30, 230, 341, 201))
        self.lbl_img.setStyleSheet("background-color:#fff")
        self.lbl_img.setText("")
        self.lbl_img.setObjectName("lbl_img")
        self.cbox_fun = QtWidgets.QComboBox(Form)
        self.cbox_fun.setGeometry(QtCore.QRect(170, 70, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbox_fun.setFont(font)
        self.cbox_fun.setStyleSheet("background-color:#fff;")
        self.cbox_fun.setObjectName("cbox_fun")
        self.cbox_fun.addItem("")
        self.cbox_fun.addItem("")
        self.cb_box_module = QtWidgets.QComboBox(Form)
        self.cb_box_module.setGeometry(QtCore.QRect(380, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_box_module.setFont(font)
        self.cb_box_module.setStyleSheet("background-color:#fff;")
        self.cb_box_module.setObjectName("cb_box_module")
        self.cb_box_module.addItem("")
        self.cb_box_module.addItem("")
        self.cb_box_module.addItem("")
        self.cb_box_module.addItem("")
        self.btn_byh_start = QtWidgets.QPushButton(Form)
        self.btn_byh_start.setGeometry(QtCore.QRect(210, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_start.setFont(font)
        self.btn_byh_start.setStyleSheet("background-color:rgb(223, 201, 104);")
        self.btn_byh_start.setObjectName("btn_byh_start")
        self.btn_byh_stop = QtWidgets.QPushButton(Form)
        self.btn_byh_stop.setGeometry(QtCore.QRect(460, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_stop.setFont(font)
        self.btn_byh_stop.setStyleSheet("background-color:rgb(223, 201, 104);")
        self.btn_byh_stop.setObjectName("btn_byh_stop")
        self.btn_byh_continue = QtWidgets.QPushButton(Form)
        self.btn_byh_continue.setGeometry(QtCore.QRect(460, 120, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_continue.setFont(font)
        self.btn_byh_continue.setStyleSheet("background-color:rgb(223, 201, 104);")
        self.btn_byh_continue.setObjectName("btn_byh_continue")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_byh_02.setText(_translate("Form", "Chỉnh tốc độ"))
        self.btn_byh_set.setText(_translate("Form", "Đặt"))
        self.cb_motor.setItemText(0, _translate("Form", "Động cơ 1"))
        self.cb_motor.setItemText(1, _translate("Form", "Động cơ 2"))
        self.cb_motor.setItemText(2, _translate("Form", "Động cơ 3"))
        self.cb_motor.setItemText(3, _translate("Form", "Động cơ 4"))
        self.cb_motor.setItemText(4, _translate("Form", "Động cơ 5"))
        self.cb_motor.setItemText(5, _translate("Form", "Động cơ 6"))
        self.cb_motor.setItemText(6, _translate("Form", "Động cơ 7"))
        self.cb_motor.setItemText(7, _translate("Form", "Động cơ 8"))
        self.cb_motor.setItemText(8, _translate("Form", "Động cơ 9"))
        self.cb_motor.setItemText(9, _translate("Form", "Động cơ 10"))
        self.btn_byh_up.setText(_translate("Form", "Trên"))
        self.btn_byh_left.setText(_translate("Form", "Trái"))
        self.btn_byh_down.setText(_translate("Form", "Dưới"))
        self.btn_byh_right.setText(_translate("Form", "Phải"))
        self.lbl_byh_05.setText(_translate("Form", "Hướng phân loại"))
        self.lbl_byh_03.setText(_translate("Form", "Loại hàng"))
        self.lbl_byh_04.setText(_translate("Form", "Số lượng"))
        self.lbl_byh_01.setText(_translate("Form", "Thủ công"))
        self.btn_byh_back.setText(_translate("Form", "Chuyển chế độ"))
        self.lbl_byh_6.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_byh_4.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_byh_2.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_byh_3.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_byh_5.setText(_translate("Form", "Thông tin hàng"))
        self.cbox_fun.setItemText(0, _translate("Form", "Theo module"))
        self.cbox_fun.setItemText(1, _translate("Form", "Theo từng động cơ"))
        self.cb_box_module.setItemText(0, _translate("Form", "Module 1"))
        self.cb_box_module.setItemText(1, _translate("Form", "Module 2"))
        self.cb_box_module.setItemText(2, _translate("Form", "Module 3"))
        self.cb_box_module.setItemText(3, _translate("Form", "Module 4"))
        self.btn_byh_start.setText(_translate("Form", "Bắt đầu"))
        self.btn_byh_stop.setText(_translate("Form", "Tạm dừng"))
        self.btn_byh_continue.setText(_translate("Form", "Tiếp tục"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
