# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'byhandwork.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1171, 695)
        Form.setStyleSheet("background-color:rgb(235, 238, 255)")
        self.lbl_byh_02 = QtWidgets.QLabel(Form)
        self.lbl_byh_02.setGeometry(QtCore.QRect(30, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_02.setFont(font)
        self.lbl_byh_02.setStyleSheet("background-color:#fff;")
        self.lbl_byh_02.setObjectName("lbl_byh_02")
        self.btn_byh_set = QtWidgets.QPushButton(Form)
        self.btn_byh_set.setGeometry(QtCore.QRect(480, 70, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_set.setFont(font)
        self.btn_byh_set.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_set.setObjectName("btn_byh_set")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(180, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color:#fff;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btn_byh_up = QtWidgets.QPushButton(Form)
        self.btn_byh_up.setGeometry(QtCore.QRect(590, 180, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_up.setFont(font)
        self.btn_byh_up.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_up.setObjectName("btn_byh_up")
        self.btn_byh_left = QtWidgets.QPushButton(Form)
        self.btn_byh_left.setGeometry(QtCore.QRect(500, 220, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_left.setFont(font)
        self.btn_byh_left.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_left.setObjectName("btn_byh_left")
        self.btn_byh_down = QtWidgets.QPushButton(Form)
        self.btn_byh_down.setGeometry(QtCore.QRect(590, 260, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_down.setFont(font)
        self.btn_byh_down.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_down.setObjectName("btn_byh_down")
        self.btn_byh_right = QtWidgets.QPushButton(Form)
        self.btn_byh_right.setGeometry(QtCore.QRect(670, 220, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_right.setFont(font)
        self.btn_byh_right.setStyleSheet("background-color:rgb(255, 255, 127);")
        self.btn_byh_right.setObjectName("btn_byh_right")
        self.lbl_byh_05 = QtWidgets.QLabel(Form)
        self.lbl_byh_05.setGeometry(QtCore.QRect(540, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_05.setFont(font)
        self.lbl_byh_05.setStyleSheet("background-color:#fff;")
        self.lbl_byh_05.setObjectName("lbl_byh_05")
        self.lbl_byh_03 = QtWidgets.QLabel(Form)
        self.lbl_byh_03.setGeometry(QtCore.QRect(30, 140, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_03.setFont(font)
        self.lbl_byh_03.setStyleSheet("background-color:#fff;")
        self.lbl_byh_03.setObjectName("lbl_byh_03")
        self.lbl_byh_04 = QtWidgets.QLabel(Form)
        self.lbl_byh_04.setGeometry(QtCore.QRect(70, 400, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_byh_04.setFont(font)
        self.lbl_byh_04.setStyleSheet("background-color:#fff;")
        self.lbl_byh_04.setObjectName("lbl_byh_04")
        self.lbl_byh_01 = QtWidgets.QLabel(Form)
        self.lbl_byh_01.setGeometry(QtCore.QRect(30, 10, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_byh_01.setFont(font)
        self.lbl_byh_01.setStyleSheet("background-color:rgb(200, 255, 176);")
        self.lbl_byh_01.setObjectName("lbl_byh_01")
        self.btn_byh_back = QtWidgets.QPushButton(Form)
        self.btn_byh_back.setGeometry(QtCore.QRect(670, 20, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_byh_back.setFont(font)
        self.btn_byh_back.setStyleSheet("background-color:rgb(85, 255, 127)")
        self.btn_byh_back.setObjectName("btn_byh_back")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(360, 70, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color:#fff;")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tbl_quantity = QtWidgets.QTableWidget(Form)
        self.tbl_quantity.setGeometry(QtCore.QRect(170, 400, 421, 271))
        self.tbl_quantity.setStyleSheet("background-color:rgb(251, 255, 205)")
        self.tbl_quantity.setRowCount(5)
        self.tbl_quantity.setColumnCount(4)
        self.tbl_quantity.setObjectName("tbl_quantity")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(930, 90, 211, 70))
        self.textEdit.setStyleSheet("background-color:#fff;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setGeometry(QtCore.QRect(930, 520, 211, 70))
        self.textEdit_5.setStyleSheet("background-color:#fff;")
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(930, 420, 211, 70))
        self.textEdit_4.setStyleSheet("background-color:#fff;")
        self.textEdit_4.setObjectName("textEdit_4")
        self.lbl_auw_7 = QtWidgets.QLabel(Form)
        self.lbl_auw_7.setGeometry(QtCore.QRect(760, 520, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_7.setFont(font)
        self.lbl_auw_7.setStyleSheet("background-color:#fff;")
        self.lbl_auw_7.setObjectName("lbl_auw_7")
        self.lbl_auw_5 = QtWidgets.QLabel(Form)
        self.lbl_auw_5.setGeometry(QtCore.QRect(760, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_5.setFont(font)
        self.lbl_auw_5.setStyleSheet("background-color:#fff;")
        self.lbl_auw_5.setObjectName("lbl_auw_5")
        self.lbl_auw_3 = QtWidgets.QLabel(Form)
        self.lbl_auw_3.setGeometry(QtCore.QRect(760, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_3.setFont(font)
        self.lbl_auw_3.setStyleSheet("background-color:#fff;")
        self.lbl_auw_3.setObjectName("lbl_auw_3")
        self.lbl_auw_4 = QtWidgets.QLabel(Form)
        self.lbl_auw_4.setGeometry(QtCore.QRect(760, 200, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_4.setFont(font)
        self.lbl_auw_4.setStyleSheet("background-color:#fff;")
        self.lbl_auw_4.setObjectName("lbl_auw_4")
        self.lbl_auw_6 = QtWidgets.QLabel(Form)
        self.lbl_auw_6.setGeometry(QtCore.QRect(760, 420, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_auw_6.setFont(font)
        self.lbl_auw_6.setStyleSheet("background-color:#fff;")
        self.lbl_auw_6.setObjectName("lbl_auw_6")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(930, 200, 211, 70))
        self.textEdit_2.setStyleSheet("background-color:#fff;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(930, 310, 211, 70))
        self.textEdit_3.setStyleSheet("background-color:#fff;")
        self.textEdit_3.setObjectName("textEdit_3")
        self.lbl_img = QtWidgets.QLabel(Form)
        self.lbl_img.setGeometry(QtCore.QRect(170, 150, 311, 191))
        self.lbl_img.setStyleSheet("background-color:#fff")
        self.lbl_img.setText("")
        self.lbl_img.setObjectName("lbl_img")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_byh_02.setText(_translate("Form", "Tốc độ động cơ"))
        self.btn_byh_set.setText(_translate("Form", "Đặt"))
        self.comboBox.setItemText(0, _translate("Form", "Động cơ 1"))
        self.comboBox.setItemText(1, _translate("Form", "Động cơ 2"))
        self.comboBox.setItemText(2, _translate("Form", "Động cơ 3"))
        self.comboBox.setItemText(3, _translate("Form", "Động cơ 4"))
        self.comboBox.setItemText(4, _translate("Form", "Động cơ 5"))
        self.comboBox.setItemText(5, _translate("Form", "Động cơ 6"))
        self.comboBox.setItemText(6, _translate("Form", "Động cơ 7"))
        self.comboBox.setItemText(7, _translate("Form", "Động cơ 8"))
        self.comboBox.setItemText(8, _translate("Form", "Động cơ 9"))
        self.comboBox.setItemText(9, _translate("Form", "Động cơ 10"))
        self.btn_byh_up.setText(_translate("Form", "Trên"))
        self.btn_byh_left.setText(_translate("Form", "Trái"))
        self.btn_byh_down.setText(_translate("Form", "Dưới"))
        self.btn_byh_right.setText(_translate("Form", "Phải"))
        self.lbl_byh_05.setText(_translate("Form", "Hướng phân loại"))
        self.lbl_byh_03.setText(_translate("Form", "Loại hàng"))
        self.lbl_byh_04.setText(_translate("Form", "Số lượng"))
        self.lbl_byh_01.setText(_translate("Form", "Thủ công"))
        self.btn_byh_back.setText(_translate("Form", "Quay lại"))
        self.lbl_auw_7.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_5.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_3.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_4.setText(_translate("Form", "Thông tin hàng"))
        self.lbl_auw_6.setText(_translate("Form", "Thông tin hàng"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
